apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: 962962113606.dkr.ecr.us-west-1.amazonaws.com/appreposfortrainingtrinet:springboot-microservice-latest
        ports:
        - containerPort: 8080